name: Autocoder with DeepSeek

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  run-autocoder:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set permissions for script.sh
        run: chmod +x scripts/script.sh

      - name: Generate Code with ChatGPT
        id: generate_code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          # first env key: value
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}      # second env key: value
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          ./scripts/script.sh "$GITHUB_TOKEN" "$REPOSITORY" "$ISSUE_NUMBER" "$OPENAI_API_KEY"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4                      # action to upload an artifact
        with:                                                 # params:
          name: autocoder-artifact                            # inputs
          path: autocoder-bot/                                # inputs

      - name: Display Generated Code using the ls command
        run: ls -R autocoder-bot/                             # output code
