name: generate-code

on:
  issues:
    types: [opened, reopened, labeled]
    
permissions:
  contents: read
  actions: write
  
jobs:
  run-autocoder:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set permissions for script.sh
        run: chmod +x scripts/script.sh

      - name: Generate Code with ChatGPT
        id: generate_code
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/script.sh $ISSUE_NUMBER $REPO $OPENAI_API_KEY

      - name: Upload Artifact
        uses: actions/upload-artifact@v4                      # action to upload an artifact
        with:                                                 # params:
          name: autocoder-artifact                            # inputs
          path: autocoder-bot/                                # inputs

      - name: List Files Recursively
        run: |
          echo "Listing all files in autocoder-artifact directory:"
          ls -R autocoder-artifact/
